---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse-role

- name: Install and configure Vector
  hosts: vector
  become: true
  vars:
    clickhouse_host: "{{ hostvars['clickhouse-01']['ansible_host'] }}"
  roles:
    - vector-role

- name: Install and configure Lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse-role