---
all:
  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 81.26.189.182
          ansible_user: ch-nikolay
          ansible_ssh_private_key_file: /home/vagrant/.ssh/ssh-key-1761056932263          
    vector:
      hosts:
        vector-01:
          ansible_host: 81.26.185.33
          ansible_user: vector-nikolay
          ansible_ssh_private_key_file: /home/vagrant/.ssh/ssh-key-1761056932263          
    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 158.160.210.208
          ansible_user: lh-nikolay
          ansible_ssh_private_key_file: /home/vagrant/.ssh/ssh-key-1761056932263
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'